# Flyway config for the E-COMMERCE model.
flyway.url=jdbc:postgresql://postgres:5432/flyway_ecommerce
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:/flyway/sql/ecommerce
flyway.schemas=public
flyway.baselineOnMigrate=true
