flyway.url=jdbc:postgresql://postgres:5432/flyway_library
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:/flyway/sql/library
flyway.schemas=public
flyway.baselineOnMigrate=true
